### ISSUE TITLE
Reset Wallet Password

### ISSUE THREAD

**Issue by ikhub** [clemahieu/raiblocks#118]
I had saved a password and locked my wallet but cannot recall the password. What is the way to reset the password?

**Comment by clemahieu** [comment]
The password is used as an encryption key; there is no way to reset it.

You will need to restore from your seed.

**Comment by ikhub** [comment]
Is there a way to access the seed if the wallet is locked?

**Comment by clemahieu** [comment]
No. The password encrypts the seed.
