### ISSUE TITLE
block missing

### ISSUE THREAD

**Issue by baundul** [clemahieu/raiblocks#13]
![see it](https://cloud.githubusercontent.com/assets/18593897/14947404/c781813e-1054-11e6-9ce5-7d32f422e5d4.jpg)

i send 9k mrai but he have not get.

hash no       CD50395C93ED4BA159AE37B8806270F81CD2AE75CC48CFCD3A0FDF563447427F

**Comment by baundul** [comment]
please, suggestion.

**Comment by SergiySW** [comment]
Your block count is correct? Advanced button -> Block count
Compare to this number: https://raiblocks.net/#/explorer

If not, try to check Advanced -> Peers -> Refresh and check how many peers you are connected to. Paste ::ffff:72.47.233.119:7075 and Initiate Bootstrap.
Restart and unlock your wallet.

**Comment by baundul** [comment]
thanks, thats going.

**Comment by baundul** [comment]
hi
