### ISSUE TITLE
Do not want to sync rai wallet 7.8.4

### ISSUE THREAD

**Issue by abahMGC** [clemahieu/raiblocks#131]
hello i'm new in railblock , i already install wallet
what should i do to synchronize my wallet to active?

its already around 6 hours, but nothing happen in my wallet
![capture](https://cloud.githubusercontent.com/assets/29006221/26524387/67d880a8-435b-11e7-842a-aa500ed5195b.PNG)

**Comment by ivijulsc** [comment]
were you able to sync your wallet? How long did it take you?

**Comment by clemahieu** [comment]
Please try version 7.8.5 https://github.com/clemahieu/raiblocks/releases/tag/V7.8.5
