### ISSUE TITLE
Invalid Claim

### ISSUE THREAD

**Issue by DeVoresyah** [clemahieu/raiblocks#135]
There is often a problem of "Invalid Claim" when the captcha I entered is valid. Need help

**Comment by SergiySW** [comment]
I guess it shouldn't be here. Wallet is not faucet

**Comment by nylazormalaca** [comment]
And my problem is the faucet refresh always.

**Comment by elle1987** [comment]
I have the same problem, the page always refresh and the captchas showed slowly not like the firt time i enter here. Please help what to do. The site really helped me alot. Tnx
