### ISSUE TITLE
Erase all numbers before 1 Rai import

### ISSUE THREAD

**Issue by mikerow** [clemahieu/raiblocks#17]
There are 10^24 possibile combination before 1 Rai value.
These numbers can be used to store information, making chain heavier for non-transfer money usage.

If client make all number before 1 Rai to 0, and nodes reject tx with non 0 before 1 Rai should be a good solution.

**Comment by clemahieu** [comment]
When counting how much space the amount takes per transaction I look at the size of a send + receive block.

Send:
256 bits - Previous hash
256 bits - Destination account
128 bits - Amount
512 bits - Signature

Receive:
256 bits - Previous hash
256 bits - Source hash
512 bits - Signature

A full transaction, send + receive takes 2176 bits, shaving 64 bits off of the amount field would be a savings of about 3%.

**Comment by mikerow** [comment]
Hi, I'm sorry if I explained myself wrong.
The "possible" problem could be caused by a system like this (my site, not spam) https://raiblockscommunity.net/news/?p=149.

The question is not "save space", the question would be avoid that space could be used for something different from simple send-receive value.

I'm not talking about "erase" 10^24 values, but just allow tx that have only zeroes in that values.
If not clear, I'll try to explain with others words. Thank you

**Comment by clemahieu** [comment]
Why would we want to disallow people using it for other things?  Block chain size?  I don't think it should be used for other things but it doesn't seem to bother me.

**Comment by mikerow** [comment]
The only reason was to mantain RaiBlocks "the simplest way to send / receive a value", without the risk to become like Bitcoin which is being used for write post, etc... .

RaiBlocks -> only receive and send value, that was the reason. But if it doesn't bother you, It doesn't bother me too.
