### ISSUE TITLE
Error deserializing config

### ISSUE THREAD

**Issue by hamiltino** [clemahieu/raiblocks#179]
Trying to start the rai_node daemon, i have followed these steps:

./rai_node --daemon
sed -i 's/"rpc_enable": "false"/"rpc_enable": "true"/g' ~/RaiBlocks/config.json
sed -i 's/"enable_control": "false"/"enable_control": "true"/g' ~/RaiBlocks/config.json

Launch rai_node in test mode
./rai_node --daemon

I get the error: "Error deserializing config"

any help appreciated:

**Comment by SergiySW** [comment]
delete config.json & try again

**Comment by hamiltino** [comment]
thanks works now
