### ISSUE TITLE
Block count for an account

### ISSUE THREAD

**Issue by mikerow** [clemahieu/raiblocks#18]
Chance to get the number of blocks for each account, without using "chain" call which return hash too.

**Comment by clemahieu** [comment]
Yes, this would be easy and make it more efficient.  A new RPC and test that takes in an account number or hash and counts the number of previous-links until the open block; the RPC would return the count.

**Comment by clemahieu** [comment]
6dc7d236761c4b519066c575ec8da08be5e646ff
