### ISSUE TITLE
Wallet help - Forgotten Password but have seed

### ISSUE THREAD

**Issue by MrGaryB** [clemahieu/raiblocks#197]
Hi,

I have forgotten my password to my wallet between having my new son arrive and today (2 weeks later). I have my seed, but I don't seem to be able to use it without entering my password first.

I have tried all my various standard passwords and I'm confused as to why it would be anything different. However, it is what is is and now I'm stuck. Can anyone advise me on what to do please?

Thanks

**Comment by s11m8** [comment]
After restoring the wallet with your seed, try using an empty password to unlock the wallet.

**Comment by MrGaryB** [comment]
Reinstalled wallet. Problem solved.
