### ISSUE TITLE
Add in config.json the possibility to disable incoming tx

### ISSUE THREAD

**Issue by mikerow** [clemahieu/raiblocks#20]
IDK if it's needed. But i suppose that a node that hosts an account with a delegate PoS (so without own funds) can be slowed or crashed if while voting it's filled (like a DoS) of incoming tx which require a lot of computing time.

If yes, maybe could be add a paramater to disable processing incoming tx for a node or a wallet or a account in config.json

**Comment by clemahieu** [comment]
The receive_minimum can be set to the highest value, 2 ^ 128 - 1, and it will never generate a receive block.
