### ISSUE TITLE
Block count in header is reversed

### ISSUE THREAD

**Issue by pocesar** [clemahieu/raiblocks#218]
The tooltip says:

![image](https://user-images.githubusercontent.com/461084/33832298-bceffba0-de62-11e7-9d3d-a4a179c1a7ad.png)

but it's the other way around

**Comment by pRizz** [comment]
The number on the left is how many blocks have been downloaded and processed. The number of the right is the number of downloaded, yet unprocessed blocks. At least that is my understanding.

**Comment by pocesar** [comment]
ah ok, because when starting from scratch, the number outside parentheses are smaller, eventually it becomes bigger
