### ISSUE TITLE
Wallet sending transaction with 0 xrb 

### ISSUE THREAD

**Issue by gp2112** [clemahieu/raiblocks#219]
I bought 45.4545 XRB today with a person. But when he sent it to me, at first time, he sent just 45 XRB unintentionally. When he was sending the rest of the value (0.4545 XRB), the wallet made a block with 0 XRB! An it was no warning. These are the block's hashes:

-     E8ABED2E8FE8FAF40EC98E0FA3D06102F15A0CF51689FBBD0593EF354BAA7593
-     91B7802D027583836D876CF4F2865E0C40A64DE73EF4911B3E29570A42B0DA34
-     689298430280B0DFF02F85FCDC722A93C52937F8C1896B2B2E1A3C6BF23D478F

Besides this issue, i'm afraid this can be used to flood the network.

**Comment by benruijl** [comment]
Perhaps decimals aren't supported yet. If you switch to kxrb in Advanced you may be able to transfer it.

**Comment by gp2112** [comment]
Yeah, I think the temporary solution is to use krai, etc...
Thank you!
