### ISSUE TITLE
Retrieve online nodes

### ISSUE THREAD

**Issue by mikerow** [clemahieu/raiblocks#22]
I would like to create a page here (https://raiblockscommunity.net/page/applications.php) to display all online nodes.

I checked RPC commands and rai_node --help commands but seems to be no way to retrieve them (except from the GUI/Peers).

It's not necessary feature, but if is possible to retrieve them it would be a fine page. Thank you.

**Comment by clemahieu** [comment]
The documentation for this RPC is missing.  action=peers should return a list of peers.

**Comment by mikerow** [comment]
I've updated the RPC documentation with the new "peers" action.

I've created the page where you can view all connected peers: https://raiblockscommunity.net/page/peers.php
