### ISSUE TITLE
Can't clone repo properly

### ISSUE THREAD

**Issue by pRizz** [clemahieu/raiblocks#229]
I tried doing a full clone of the repo and got this error.

```
Cloning into 'lmdb'...
fatal: reference is not a tree: a036f6572b58c00daaf8d3efcf933a926989007d
Unable to checkout 'a036f6572b58c00daaf8d3efcf933a926989007d' in submodule path 'lmdb'
Completed with errors, see above.
```

and after doing a submodule update
```
$ git submodule update
fatal: reference is not a tree: a036f6572b58c00daaf8d3efcf933a926989007d
Unable to checkout 'a036f6572b58c00daaf8d3efcf933a926989007d' in submodule path 'lmdb'
```

**Comment by clemahieu** [comment]
I tried pushing again, can you see if that fixed it?

**Comment by pRizz** [comment]
@clemahieu still getting the same error

**Comment by pRizz** [comment]
Fixed it here https://github.com/clemahieu/raiblocks/pull/231

**Comment by pRizz** [comment]
I realized my mistake. I was pulling from my own fork instead of the main repo, which is why I wasn't experiencing your fix @clemahieu . My apologies for the confusion.

**Comment by clemahieu** [comment]
No problem, the more people looking at things the better.
