### ISSUE TITLE
[Feature] Disable "Unlock" button when unlocked and "Lock" button when locked

### ISSUE THREAD

**Issue by pramttl** [clemahieu/raiblocks#237]
### Details

There are 2 buttons in the desktop Mac wallet, Unlock / Lock. Both seem enabled at all times. They could be enabled or disabled depending on the lock state. It is confusing to try to unlock the wallet when it's already unlocked.

### Snapshot

<img width="339" alt="screen shot 2017-12-16 at 8 02 11 pm" src="https://user-images.githubusercontent.com/933802/34076426-0adb1c36-e29c-11e7-9493-5ba6ac70df0d.png">

### Version
8.0.0

**Comment by DarthWindu** [comment]
Hmm I'll look into this

**Comment by dannyvankooten** [comment]
:+1: 

I suggested something along these lines in #279 as well, after not understanding why "Lock" did not work for me (as I was filling in the password field).
