### ISSUE TITLE
RPC command to see who delegated someone or viceversa

### ISSUE THREAD

**Issue by mikerow** [clemahieu/raiblocks#24]
In this page https://raiblockscommunity.net/history/index.php?acc=xrb_1zo54ia1363ikd4nb9ikamux3fnsnr7jurzs45xhda78o9piowa44o5zzaws I show the voting weight of an account. But there is no way to know (from RPC) to know all the account that delegated him or viceversa.

Is it a not-documented function?

**Comment by mikerow** [comment]
Is not available RPC yet, but seen that rep is cached, it could be further.

**Comment by clemahieu** [comment]
RPC to find an account's representative.  https://github.com/clemahieu/raiblocks/commit/9015df2e296c21bdeeef3791809741f0be18fcfd

RPC to find how much representation an account has
https://github.com/clemahieu/raiblocks/commit/79e5be06d467c2e1d818fb991ba525441d6abcfc
