### ISSUE TITLE
Some blocks like "change" doesn't appear in action:history

### ISSUE THREAD

**Issue by mikerow** [clemahieu/raiblocks#25]
There is no notice of this block https://raiblockscommunity.net/explorer/index.php?h=E3BFD3411F365250DF96AC53D171A671762B182D67800C1E3D14FFD6448FC5E7

In the account's history https://raiblockscommunity.net/history/index.php?acc=xrb_1133oih5pyhzpo74ey97igfa9yp89kptonethftf5oa9nsm8p77fqd19h3p4

Infact, in the above page (history), some blocks seem missed.

**Comment by SergiySW** [comment]
Looks like  { "action": "history" } doesn't show "change" block type.

**Comment by mikerow** [comment]
@SergiySW It doesn't show: change and open, while it shows only send and receive.

**Comment by mikerow** [comment]
Well, History is thought to get the in out of each payment. We don't need to see change in history. I close.
