### ISSUE TITLE
librai_lib now shared but not distributed

### ISSUE THREAD

**Issue by androm3da** [clemahieu/raiblocks#273]
Either we should also build a static `librai_lib` and link `rai_wallet` against that one or we should ship `librai_lib.{so,dll}`.

**Comment by clemahieu** [comment]
We should ship it, I just haven't gotten to adding it to the installation and tested to make sure it works.

**Comment by androm3da** [comment]
Ok.  If we ship it then we will also need the tarball to put it in the right host location for the loader to find it or (on linux at least) add an `ld.conf.d` file.

**Comment by clemahieu** [comment]
Is setting the rpath of the main executable an option before putting it in the tarball?

**Comment by androm3da** [comment]
Oh yeah that's even better
