### ISSUE TITLE
Wallet sync problem ?

### ISSUE THREAD

**Issue by coinheo** [clemahieu/raiblocks#292]
Hey, i just downloaded latest version of wallet. But block number at 57. Is there anything to do or bootstrap ?

**Comment by androm3da** [comment]
Just be extraordinarily patient.  :)

**Comment by lunixcz** [comment]
I'm syncing my newly created wallet using Linux desktop client (wallet) for more than 24 hours as of now...
Synchronizing, Block: 313600 (4263043)

Is this normal?
[log_2017-12-28_05-07-55.4.log](https://github.com/clemahieu/raiblocks/files/1590762/log_2017-12-28_05-07-55.4.log)

**Comment by lunixcz** [comment]
Now it states:
Running, Block: 313603 (4266505)
but it's apprently not synced up to latest block.. and considering another 5 hours of syncing from my last post there is very little progress. It doesn't not seem like this is going to be finished any time soon.

**Comment by groach** [comment]
Follow this tutorial. Only difference for linux is location of ldb file: /home/<user>/RaiBlocks/

https://steemit.com/utopian-io/@ankarlie/tutorial-how-to-install-the-raiblock-desktop-wallet-with-synchronization-short-cut

**Comment by coinheo** [comment]
What about macOS ? is it suitable ?

**Comment by citizen2077** [comment]
The best latest guide for quick syncing by downloading the ledger is on the Raiblocks official reddit daily discussion page, at the bottom of the main post: https://www.reddit.com/r/RaiBlocks/comments/7ml95j/faq_daily_general_discussion_december_28_2017/

**Comment by groach** [comment]
Yes. Only difference is location of ldb file. It’s in Library/RaiBlocks

**Comment by coinheo** [comment]
Thanks, i just handled!
