### ISSUE TITLE
Adding an overload to namespace std with a non-user-defined type

### ISSUE THREAD

**Issue by thelostt** [clemahieu/raiblocks#331]
[This](https://github.com/clemahieu/raiblocks/blob/master/rai/node/node.cpp#L2634) code specifically:

```c++
std::ostream & operator << (std::ostream & stream_a, std::chrono::system_clock::time_point const & time_a)
```

contains undefined behavior as per [[namespace.std]/1](http://eel.is/c++draft/namespace.std#1):

> The behavior of a C++ program is undefined if it adds declarations or definitions to namespace std or to a namespace within namespace std unless otherwise specified.
A program may add a template specialization for any standard library template to namespace std only if the declaration depends on a user-defined type and the specialization meets the standard library requirements for the original template and is not explicitly prohibited.

[[namespace.std]/3](http://eel.is/c++draft/namespace.std#3.sentence-2) also applies:

> A program may explicitly instantiate a template defined in the standard library only if the declaration depends on the name of a user-defined type and the instantiation meets the standard library requirements for the original template.

The fix would be to wrap `std::chrono::system_clock::time_point` inside a user-defined type (such as a struct/class).

**Comment by androm3da** [comment]
> The fix would be to wrap std::chrono::system_clock::time_point inside a user-defined type (such as a struct/class).

Great, make a PR!  :)
