### ISSUE TITLE
Illegal hardware instruction when starting rai_wallet on Arch Linux

### ISSUE THREAD

**Issue by MilkyPL** [clemahieu/raiblocks#337]
When I try to start rai_wallet, nothing happens. Tried running it from terminal and got this:
`zsh: illegal hardware instruction (core dumped)  rai_wallet`

Here is the core dump from `coredumpctl`:
```
❯ coredumpctl info 8761
           PID: 8761 (rai_wallet)
           UID: 1000 (jakub)
           GID: 1000 (jakub)
        Signal: 4 (ILL)
     Timestamp: Sat 2017-12-30 12:26:50 CET (11min ago)
  Command Line: rai_wallet
    Executable: /usr/bin/rai_wallet
 Control Group: /user.slice/user-1000.slice/session-c7.scope
          Unit: session-c7.scope
         Slice: user-1000.slice
       Session: c7
     Owner UID: 1000 (jakub)
       Boot ID: 63c9a19d9da04947a0a4baadaa35a760
    Machine ID: e5d2fc6556ad498b8c8099876529de96
      Hostname: cyberia
       Storage: /var/lib/systemd/coredump/core.rai_wallet.1000.63c9a19d9da04947a0a4baadaa35a760.8761.1514633210000000.lz4
       Message: Process 8761 (rai_wallet) of user 1000 dumped core.
                
                Stack trace of thread 8761:
                #0  0x000055d2f8a57a96 _ZN5boost16exception_detail27get_static_exception_objectINS0_10bad_alloc_EEENS_13exception_ptrEv (rai_wallet)
                #1  0x000055d2f8a4b1b1 n/a (rai_wallet)
                #2  0x000055d2f8cce02d __libc_csu_init (rai_wallet)
                #3  0x00007f5e47a47edb __libc_start_main (libc.so.6)
                #4  0x000055d2f8a4f24a _start (rai_wallet)
```
I'm using `raiblocks-git` from AUR.

**Comment by Dekoze** [comment]
Can you run the wallet with gdb and when it crashes paste the output of the command `disassemble $pc,+8`

**Comment by androm3da** [comment]
This binary was probably built with some `march=native`.  I think if we flipped the default of `RAIBLOCKS_SIMD_OPTIMZATIONS` it would fix bugs like this.

**Comment by tdassonville** [comment]
Maybe related to #253 ?
I got a similar issue on an Atom based machine, for rai_node... Fixed by rebuilding from master with cmake's RAIBLOCKS_SIMD_OPTIMIZATIONS=OFF and CRYPTOPP_CUSTOM=ON.

Hope this helps...

**Comment by slact** [comment]
@MilkyPL hey, i'm the maintainer of the raiblocks-git Arch linux package. can you paste your `/proc/cpuinfo` ? There's sensing for AVX2 optimizations in the build tool, but nothing else yet.

**Comment by androm3da** [comment]
@slact we have arch in the CI suite -- do you want to include arch packaging there too?

**Comment by slact** [comment]
@androm3da yep, good idea. Here's the package: https://aur.archlinux.org/raiblocks-git.git I'll check out how to merge it into the CI suite.
