### ISSUE TITLE
ambiguous boost instructions

### ISSUE THREAD

**Issue by jeanmw** [clemahieu/raiblocks#345]
The build instructions specify boost version 1.63, but this is not available if you're installing with homebrew - the nearest available versions through brew are `boost@1.60` and the newest version of boost, 1.66. If you try to install via manual download as recommended instead (http://www.boost.org/users/history/version_1_63_0.html), it will take anywhere from 5 to 7 minutes.
Ideally, the project should either specify more specific instructions for how to install a specific version of boost to a specific dir on linux/windows/mac, or the project should use a version of boost easily

**Comment by brendanw** [comment]
I also resorted to using homebrew to install boost@1.65.1 which is compatible with raiblocks. It would be great if the instruction set for getting boost@1.63 setup were a bit more specific for those of us who are eager to contribute but haven't worked on c++ in a while. Just the fact that boost uses square brackets in its directory name threw me for a loop.

**Comment by theronic** [comment]
This may be relevant: https://github.com/EOSIO/eos/pull/1012/commits/b56edc728d35cc76085d5e38823ef1fac2aa11a6

**Comment by jeanmw** [comment]
Hey - awesome yet that fixed it. For those of you also using brew, boost@1.66 (latest version) is compatible. Thanks @theronic

**Comment by jeanmw** [comment]
However - looks like there are still conflicts with boost 1.66 and beast when building. One is a conflict with a class redeclaration of `io_service`, another with a template redeclaration.
