### ISSUE TITLE
How to move blockchain data to another drive?

### ISSUE THREAD

**Issue by midas717** [clemahieu/raiblocks#346]
Don't have anymore space on my C: drive for blockchain data. How can I move it to my other drive and store it there?

**Comment by jdereynal** [comment]
A symbolic link does the trick. 
Move the Raiblocks folder to your other drive, then enter this command (for Windows) :
`mklink /j C:\Users\<yourname>\AppData\RaiBlocks <folder location>`

**Comment by midas717** [comment]
it's AppData\Local\RaiBlocks, but thanks!! exactly what i was looking for
