### ISSUE TITLE
RaiBlocks meetup groups

### ISSUE THREAD

**Issue by donutloop** [clemahieu/raiblocks#357]
The goal of this groups is to facilitate the exchange of information about the RaiBlocks technologies and to find more programmers for that project.

Proposal:
- events and workshops to help people understand the basic concepts
- social meetups to get to know each other

What do we need for that? 

- Hoster 
- Organizer
- Volunteers
- An account on meetup.com

https://www.meetup.com/

**Comment by tomstuchinski** [comment]
I don't think the github "issues" page is the appropriate place for this sort of announcement. Please consider posting this elsewhere (perhaps the RaiBlocks subreddit) instead.

**Comment by donutloop** [comment]
Actually, we do need then a meetup link on the website if anyone is interested to do it.

Feel free to contribute to this thread:

https://www.reddit.com/r/RaiBlocks/comments/7nh66y/raiblocks_meetup_groups/

**Comment by AyiSoli** [comment]
You can close this issue as it is not technical
