### ISSUE TITLE
INVALID BLOCK error message during the transfer

### ISSUE THREAD

**Issue by radioactiviti** [clemahieu/raiblocks#361]
Seems like a common and wide issue.  I transferred 100 XRB from BitGrail to RaiWallet. 
The transaction seems complete from BitGrail, but the tracking history says "Invalid Block"

Let me know if you need additional info

**Comment by gysi** [comment]
Same problem here. Transferred 1 XRB fom Bitgrail to my wallet:
![image](https://user-images.githubusercontent.com/1576445/34472355-c46d1304-ef60-11e7-8cc2-b0f4c633ef99.png)

Raiblocks network says invalid block:
https://raiblocks.net/block/index.php?h=224406201843A7210B07C7B7E02DF7B35A88FC753329DE13EA56748AFAFB47CB

**Comment by Dekoze** [comment]
This is on bitgrail's end. They have yet to broadcast the TX to the network. It's never taken more than 15 minutes for me so if you've been waiting a while you can contact them through telegram or support ticket.

**Comment by gysi** [comment]
Ok, worked. Thanks!

**Comment by AyiSoli** [comment]
Related to exchanges. You can check valid blocks on the desktop wallet block viewer

**Comment by brightmonkey** [comment]
Can this issue be closed?

**Comment by androm3da** [comment]
Block explorer shows this tx as "completed".  Closing, please reopen if it's still a problem.
