### ISSUE TITLE
QR code support

### ISSUE THREAD

**Issue by cryptocode** [clemahieu/raiblocks#383]
What do you guys think about supporting QR codes in the Qt wallet?

I've been prototyping a first version to evaluate various encoding libs:

<img width="358" alt="qr-in-wallet" src="https://user-images.githubusercontent.com/34946442/34525744-4cc68e8e-f0a0-11e7-948e-7175887a891b.png">

We could support various options from https://github.com/clemahieu/raiblocks/wiki/URI-and-QR-Code-Standard as well, but the first version could simply be the XRB account address.

I guess a "Show QR code" button that opens a dialog with options is one way to do the UX? Showing it inline is a bit unwieldy.

A "back up an optionally encrypted seed to QR code" for printing on paper backup is also something I'd personally like.

**Comment by androm3da** [comment]
Heck yeah!

**Comment by rainbyte** [comment]
new gui (see issue #384) has a working implementation of this (maybe not definitive)

Screenshot here: https://i.imgur.com/1D0gqh7.png

**Comment by cryptocode** [comment]
Closing this as new desktop clients are on the way.

**Comment by rainbyte** [comment]
@cryptocode, maybe it could be useful anyways, publish it if you can... because #384 doesn't have definitive implementation yet (it uses old library)
