### ISSUE TITLE
Arch Linux (Manjaro) RaiBlocks ver: 9.0.0 - "Address family not supported by protocol"

### ISSUE THREAD

**Issue by matiwinnetou** [clemahieu/raiblocks#387]
On Arch Linux (Manjaro) rai wallet doesn't start up.

![image](https://user-images.githubusercontent.com/335933/34539801-5c9af7b4-f0d2-11e7-8f31-f5d114887aa2.png)

Bug bounty (sadly due to Bitgrail policy min 1 XRB):
xrb_1648b8yiicejzgjgbzj6rhpfkqwd1qwfat6sdpu4w857h9cm8o3bjpe5zuye

**Comment by Syd** [comment]
Not really a bug, I'm guessing ipv6 is disabled?

**Comment by androm3da** [comment]
Tracking this as #399

**Comment by matiwinnetou** [comment]
Fair enough but some users may not have IPV6...
