### ISSUE TITLE
Debian 9/Ubuntu 16.04 compile error. Clean install

### ISSUE THREAD

**Issue by lazitskiy** [clemahieu/raiblocks#390]
Hi, dear raiblocks team.

(Duplicate https://github.com/clemahieu/raiblocks/issues/386 ?
will try https://github.com/clemahieu/raiblocks/issues/386, and comment later here.
If it will be ok, i think u need fix build instruction https://github.com/clemahieu/raiblocks/wiki/Build-rai_node-samples
)

## Docker image
Get error as well, see this https://www.reddit.com/r/RaiBlocks/comments/7npy6o/has_anybody_ran_a_raiblocks_node_docker_on_a/

linked issue - https://github.com/clemahieu/raiblocks/issues/377

## Debian9

According to the instruction https://github.com/clemahieu/raiblocks/wiki/Build-rai_node-samples

```make rai_node```
gets
```
[ 91%] Building CXX object CMakeFiles/node.dir/rai/node/node.cpp.o
In file included from /root/rai_build/rai/node/node.cpp:5:0:
/root/rai_build/rai/node/rpc.hpp:7:27: fatal error: boost/beast.hpp: No such file or directory
 #include <boost/beast.hpp>
```
![image](https://user-images.githubusercontent.com/4090109/34545812-74cc9274-f100-11e7-9f8e-3ecdfcd068dd.png)

## Ubuntu 16.04
The same error. Static Boost was manually compiled

Come from here https://github.com/clemahieu/raiblocks/blob/master/rai/node/rpc.hpp#L7
Something wrong with *libboost-all-dev*?
```
root@cryptotools:~/rai_build# apt-get install libboost-all-dev -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-all-dev is already the newest version (1.62.0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Any ideas?

**Comment by SergiySW** [comment]
Sample updated. You have to build boost 1.66 for master branch

**Comment by lazitskiy** [comment]
Ok, thank u, will try and comment here in next hour

**Comment by lazitskiy** [comment]
Thats ok, boost version 1.66 fix the issue.
Compiled successfully
