### ISSUE TITLE
Add an easy way to find the balance on the block viewer

### ISSUE THREAD

**Issue by HostFat** [clemahieu/raiblocks#4]
Currently it isn't easy by a bitcoin escrow (in a 2x3 multisig trade) to read if the sender has sent the right amount of value.
This will help to increase the trading offers on p2p exchanges as [Bitsquare](https://github.com/bitsquare/bitsquare) (an example)

![image](https://cloud.githubusercontent.com/assets/644416/14671188/d7f54ce8-06f0-11e6-874f-d40f1c3e672e.png)

**Comment by clemahieu** [comment]
Added account viewer.
0213fd298914485b0058e1e40f72304b897724d3
