### ISSUE TITLE
Show complete balance of XRB in desktop wallet

### ISSUE THREAD

**Issue by yousifa** [clemahieu/raiblocks#401]
Balance in the desktop wallet does not show the full amount, for example, If I have 3.987 XRB in my wallet, it will only show 3 XRB on the desktop wallet. There is no way to see the total balance, even on the block explorer in the wallet. The online block explorer works correctly.

**Comment by dannyvankooten** [comment]
This is fixed in a695d0f52b92b74accd9dbb6284552e2f64f0599 already, via #321.

![image](https://user-images.githubusercontent.com/885856/34602392-e41b5eb2-f1ff-11e7-9524-f41f03ca9184.png)

**Comment by morninghues** [comment]
Under "Advanced", change your scale to "kxrb"

**Comment by yousifa** [comment]
This should be default set from a UX standpoint

**Comment by morninghues** [comment]
True. I'm facing even bigger issues.

**Comment by yousifa** [comment]
What’s your issue?

**Comment by dannyvankooten** [comment]
See my reply. This is improved upon in the latest development version and will be included in the next release. Patience, young padawans.

**Comment by androm3da** [comment]
This was primarily due to the rocketing exchange rate making those digits more relevant since earlier releases.

As @dannyvankooten said it's fixed on master.  Thanks.
