### ISSUE TITLE
Auto-download latest data file upon new wallet launch

### ISSUE THREAD

**Issue by yousifa** [clemahieu/raiblocks#409]
Feature request:
When wallet is launched with empty blockchain file, download latest blockchain file rather than building it from the network.

**Comment by jc-murray-1986** [comment]
@yousifa, who would you trust to provide you with the database?  One of the main objectives of crypto is to avoid trusted third parties!

**Comment by 5k1ttl3** [comment]
Bootstrapping with the database file is a SUPER hackjob band-aid fix.
This should not be encouraged, and needs to be fixed as soon as possible.
as @jc-murray-1986 suggested, we can't be in a situation where we're required to trust a central third party to provide our initial sync for us.

**Comment by yousifa** [comment]
True, but if we posted a hash of the latest database file in a known block and verify against it, it would provide a temporary safe fix for building the entire chain

**Comment by cryptocode** [comment]
IMO, dev resources are better spent making sync faster.

**Comment by yousifa** [comment]
@cryptocode I agree
