### ISSUE TITLE
xrb do not arrive in the dektop-wallet

### ISSUE THREAD

**Issue by rasu1** [clemahieu/raiblocks#410]
in the blockexplorer it says pending.....but for a long long time......several hours
adress:

xrb_1i19jnq4o1hp5t5r17esm99utq8cyirf48mhs1hbmqegqco6ginakhj316ah

**Comment by cryptocode** [comment]
@rasu1 Read the FAQ https://www.reddit.com/r/RaiBlocks/comments/7obuxt/faq_daily_general_discussion_january_5th_2018/?st=jc2hqj6g&sh=9e38d0df

**Comment by 5k1ttl3** [comment]
Is your desktop wallet fully sync'd?
It needs to be synchronized. Once it is, unlock the wallet and the funds should be accepted

**Comment by jondwillis** [comment]
@rasu1 See https://mega.nz/#F!oPwQ0S7C!7ly7_rIyT1CEKSsBh1N4OA!kDASWYaS

This link contains instructions and daily block lattice snapshots from the core developers.

**Comment by 5k1ttl3** [comment]
@rasu1 make sure you back up your wallet first. Importing that DB will wipe your config.

**Comment by rasu1** [comment]
hello,

i tryed so many things now:

waiting

installing in program x86

installing on a ram disk

downloading the blockchain and paste it in

it is always the same:

the number of blocks to synchronisize increases about 1000 per hour, so it  
will never end with it....


possibly an older version of the wallet works better?

thanks for answering

rasu1


Am 06.01.2018, 02:14 Uhr, schrieb 5k1ttl3 <notifications@github.com>:

> @rasu1 make sure you back up your wallet first. Importing that DB will  
> wipe your config.
>


-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/

**Comment by rasu1** [comment]
hello,

it is solved!

after pasting the downloaded blockchain it took about 30 min, and now it  
works,
my purchase arrived!
thanks for help!

better u give the blockchain with the walletdownload in the future i  
think.....

best regards,
rasu1



Am 06.01.2018, 02:14 Uhr, schrieb 5k1ttl3 <notifications@github.com>:

> @rasu1 make sure you back up your wallet first. Importing that DB will  
> wipe your config.
>


-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/
