### ISSUE TITLE
Crashes when running on TAILS v3.3

### ISSUE THREAD

**Issue by george-viaud** [clemahieu/raiblocks#449]
Wallet crashes with 'Illegal Instruction' when attempting to execute binary on TAILS v3.3

**Comment by androm3da** [comment]
The existing releases are optimized for particular architectures.

We will release unoptimized binaries (and probably also optimized ones) next time 'round, sorry.

For now you can rebuild from source.

**Comment by george-viaud** [comment]
Do you have a guide available for building from source on `nix?  I must admit (embarrassingly) that the current instructions are vague as I've not constructed CMakeLists manually before and I'm unsure what the to do with the config lines in the link referred to in the README.md

Thank you for the reply and direction

**Comment by androm3da** [comment]
Refer to `ci/build-travis.sh` for build and `ci/ubuntu_prep.sh` for getting dependencies installed.

**Comment by george-viaud** [comment]
Many thanks for this - very helpful!

What I'm running into now appears to be boost dependency problems (I built boost based on https://github.com/clemahieu/raiblocks/wiki/Build-Instructions but am not sure what path and prefix to provide here).

build-travis appears to be looking in /usr/local

Elsewhere I see references to /temp/build but I think this is just for docker.

I apologize for my lack of knowledge here and again thank you for any help you are willing to lend.

Best,

George
