### ISSUE TITLE
CMake and Boost 1.66.0 on Windows

### ISSUE THREAD

**Issue by CathalT** [clemahieu/raiblocks#481]
**Steps to reproduce the issue:**

1. Fresh checkout on Windows.
2. Follow usual build steps
3. Try to generate proj file from CMake

**Describe the results you received:**

CMake cannot find boost 1.66.0
Project won't compile.

**Describe the results you expected:**

CMake can find boost and project compiles normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

Windows, fresh checkout with boost 1.66.0.

**Work around/Fix**
CMake needed to push a fix, which they have done as of yesterday.
https://gitlab.kitware.com/cmake/cmake/merge_requests/1625

Need to wait for next minor release or download a nightly build from:
https://cmake.org/files/dev/?C=M;O=D

Reason I'm raising this is bringing in a new boost version can cause issues with CMake and break things.
More of a heads up than anything.

Edit: In fact it may only be an issue when building boost with MSVC.

**Comment by mrwgen** [comment]
I had the same issue, 1.59 works perfectly with MSVC 14. Don't forget to change environment variables. Also, don't forget to download qt5.
