### ISSUE TITLE
rai_node default directory

### ISSUE THREAD

**Issue by Afkbio** [clemahieu/raiblocks#484]
Hi,

Just noticed on linux, the default directory is set to ~/Raiblocks for the files created by rai_node.
It should be the current directory, it's confusing

**Comment by cryptocode** [comment]
This is by design, on all OS's. Paths here:

https://github.com/clemahieu/raiblocks/wiki/RaiBlocks-folder

There's a --data_path option.

**Comment by androm3da** [comment]
Sorry, it's this way by design and it's preferable to use the user's directory as a basis over the current working dir.

As stated, you can override it.
