### ISSUE TITLE
Rai node paused.

### ISSUE THREAD

**Issue by morninghues** [clemahieu/raiblocks#492]
I'm running a rai node on my VPS and I noticed today that the storage got filled up and hence the node stopped counting blocks. How can I get it back running again?
I tried rebooting the instance and it didn't help. I also tried restarting the daemon manually but that didn't work either.

**Comment by munkyxtc** [comment]
Is there any information in your log file?  

Are you confirming blocks are not increasing by using block_count RPC or  --debug_block_count CLI commands?

**Comment by morninghues** [comment]
Okay, it's working now. It fixed itself I guess. There's a dip in CPU usage when it stopped counting, but it's working fine now.  Yes, I used --debug_block_count and can't see anything related to it in the log file.
