### ISSUE TITLE
Error starting Docker rai_node on latest Docker edge version

### ISSUE THREAD

**Issue by sacreman** [clemahieu/raiblocks#502]
**Description of bug:**

Docker run command on latest Docker edge (Version 17.12.0-ce-mac45 (21669)) on MacOS fails with the following error:

```
$ sudo docker run -d -p 7075:7075/udp -p 7075:7075 -p [::1]:7076:7076 -v ~:/root clemahieu/rai_node /rai_node --daemon
Password:
ea29924038cf1eca3ea9ec45211fb7d194ea9d6bd53dddd9f35767968e56adc4
docker: Error response from daemon: driver failed programming external connectivity on endpoint eloquent_pasteur (53649cea89f42738f61d88198ddee3ff3a411e6611db96aff368630eeb128018): Error starting userland proxy: port is not a proto:IP:port: 'tcp:[:'.
```

**Steps to reproduce the issue:**

1. Install Docker Edge on MacOS
2. Run `sudo docker run -d -p 7075:7075/udp -p 7075:7075 -p [::1]:7076:7076 -v ~:/root `

**Describe the results you received:**

Error message: `Error starting userland proxy: port is not a proto:IP:port: 'tcp:[:'.`

**Describe the results you expected:**

The container should start.

**Additional information you deem important (e.g. issue happens only occasionally):**

The latest Docker seems to have a lot of fixes for vpnkit and proxy settings. I'm guessing something got broken here.

**Environment:**

- OS: MacOS Sierra
- Node version: clemahieu/rai_node:latest
- (docker node): Docker version 17.12.0-ce, build c97c6d6

**logs**

No logs, container doesn't start.

**Comment by sacreman** [comment]
Perhaps we could use Docker tags (and create images) to allow for `:ipv4` and `:ipv6` configurations. With ipv4 being used in the quick start guide instructions when running on a somebodies laptop.

**Comment by sacreman** [comment]
As a workaround the following works:

1. Start the container.

```
docker run -d -p 7075:7075/udp -p 7075:7075 -p 7076:7076 -v ~:/root clemahieu/rai_node /rai_node --daemon
```

2. The first time it is run it will fail. However, it should have created the directory `~/Raiblocks` which has the default `config.json` inside. Edit this file and change:

`rpc_enable` to `true`
`address` to `::ffff:0.0.0.0` # This will fix the container so it starts
`enable_control` to `true`

3. Once the config.json is saved run the container for the 2nd time and it should start and stay running.

```
docker run -d -p 7075:7075/udp -p 7075:7075 -p 7076:7076 -v ~:/root clemahieu/rai_node /rai_node --daemon
```

4. Test the RPC endpoint bound to the ipv4 address.

```
$ curl -d '{ "action": "version" }' localhost:7076
{
    "rpc_version": "1",
    "store_version": "10",
    "node_vendor": "RaiBlocks 9.0"
}
```

**Comment by jcraigk** [comment]
I added a note about `-p [::1]:7076:7076` to https://github.com/clemahieu/raiblocks/wiki/Docker-node.

**Comment by orhanhenrik** [comment]
Doing -p 7076:7076 is a very bad idea! Don’t do it! Anybody on your network can now talk to your nodes RPC. Instead do -p 127.0.0.1:7076:7076

**Comment by sacreman** [comment]
Have updated my comment above and can confirm this works on latest Docker edge.

```
$ docker run -d -p 7075:7075/udp -p 7075:7075 -p 127.0.0.1:7076:7076 -v ~:/root clemahieu/rai_node /rai_node --daemon
930e201f9c985cca09b18b7b0f4beacc9fbc8a7b9772405cbd84a14bfd2fa278
```

**Comment by brianfoody** [comment]
@sacreman works a treat, thanks mate
