### ISSUE TITLE
Non-UI threads accessing UI elements in qt.cpp

### ISSUE THREAD

**Issue by CathalT** [clemahieu/raiblocks#503]
**Steps to reproduce the issue:**
1. Start GUI wallet in debug
2. Do a UI action that creates a callback on another thread.
3. QT asserts when the new thread attempts to access UI code.

**Describe the results you received:**
QT assert when non UI thread attempts to access UI code.

**Describe the results you expected:**
No asserts, callbacks should be queued on UI thread.

**Additional information you deem important (e.g. issue happens only occasionally):**
100% reproducible.

Example code:
``` c++
	QObject::connect (backup_seed, &QPushButton::released, [this]() {
		rai::raw_key seed;
		rai::transaction transaction (this->wallet.wallet_m->store.environment, nullptr, false);
		if (this->wallet.wallet_m->store.valid_password (transaction))
		{
			this->wallet.wallet_m->store.seed (seed, transaction);
			this->wallet.application.clipboard ()->setText (QString (seed.data.to_string ().c_str ()));
			show_button_success (*backup_seed);
			backup_seed->setText ("Seed was copied to clipboard");
			this->wallet.node.alarm.add (std::chrono::system_clock::now () + std::chrono::seconds (5), [this]() {
                                //Not thread safe.
				show_button_ok (*backup_seed);
				backup_seed->setText ("Copy wallet seed to clipboard");
			});
		}
		else
		{
			this->wallet.application.clipboard ()->setText ("");
			show_button_error (*backup_seed);
			backup_seed->setText ("Wallet is locked, unlock it to enable the backup");
			this->wallet.node.alarm.add (std::chrono::system_clock::now () + std::chrono::seconds (5), [this]() {
                                //Not thread safe
				show_button_ok (*backup_seed);
				backup_seed->setText ("Copy wallet seed to clipboard");
			});
		}
	});
```

when :

``` c++
this->wallet.node.alarm.add 
```
executes the lamda passed into it, its on a different thread. There are multiple cases of this in https://github.com/clemahieu/raiblocks/blob/master/rai/qt/qt.cpp

**Environment**:
Windows 8.1

If I get around to it I might try push a fix myself. (trying to develop my own light wallet currently between my day job)

**Comment by thatname** [comment]
I've met exactly the same issue too.

**Comment by thatname** [comment]
It's wrong to call this->wallet.node.alarm.add() with a lambda with qt calls in it, because the lambda is to be executed in an asio worker thread. To fix it, all calls must be replaced with QTimer::singleShot()

**Comment by cryptocode** [comment]
@thatname sounds like you're very close to making a pull request ;)
