### ISSUE TITLE
Avoid newlines in accounts & addresses, affects copy/paste

### ISSUE THREAD

**Issue by pinheadmz** [clemahieu/raiblocks#504]
**Description of bug:**
account ids are displayed over two lines in the client, adding `\n` to the middle of a copied address 

**Steps to reproduce the issue:**
1. open wallet
2. attempt to copy account address by dragging the mouse over the text displayed over two lines
3. paste somewhere

**Describe the results you received:**
Here's my account representative:
xrb_1anrzcuwe64rwxzcco8dkhpyxpi8
kd7zsjc1oeimpc3ppca4mrjtwnqposrs
^^^ If I paste that into a block explorer I get an error

**Describe the results you expected:**
xrb_1anrzcuwe64rwxzcco8dkhpyxpi8kd7zsjc1oeimpc3ppca4mrjtwnqposrs
^^^ newline removed, copy/paste is easy!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:
OSX

**logs**

**Comment by chpio** [comment]
this is fixed on *master*

**Comment by pocesar** [comment]
happens on Windows as well

**Comment by pinheadmz** [comment]
@chpio Out of curiosity, do you know how or which commit?

**Comment by chpio** [comment]
https://github.com/clemahieu/raiblocks/commit/c1b9f9491e0d93d93e376a8dc2a4f2a97877ce27
