### ISSUE TITLE
RPC "block_account" error (xrb_1111111111111111111111111111111111111111111111111111hifc8npp)

### ISSUE THREAD

**Issue by SergiySW** [clemahieu/raiblocks#51]
For some blocks "action": "block_account" returns non-existing account in answer.

Example:
`
curl -d '{ "action": "block_account", "hash": "9D3E9A9E649A6588A3A29E2129E1DF91D27183AB1BCE19F7DC273F325902BE75" }' 127.0.0.1:7076
`
returns
`{ "account": "xrb_1111111111111111111111111111111111111111111111111111hifc8npp" }`

**Comment by clemahieu** [comment]
b2b0b9b2e2171125269db6bb33e1748a2d501b3e
