### ISSUE TITLE
QTimers dependency requires newer Qt?

### ISSUE THREAD

**Issue by androm3da** [clemahieu/raiblocks#527]
Since https://github.com/clemahieu/raiblocks/pull/508 we started failing builds on Trusty.

We now have compilation errors like the one below.

@CathalT thanks so much for your contribution.  Would you be willing to rework the change with a CMake feature test or some other way to make sure it still builds on older distros?

```

/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 2 provided
../rai/qt/qt.cpp: In lambda function:
../rai/qt/qt.cpp:1415:6: error: no matching function for call to 'QTimer::singleShot(std::chrono::duration<long int, std::ratio<1l, 1000l> >::rep, rai_qt::settings::settings(rai_qt::wallet&)::__lambda73::__lambda74)'
     });
      ^
../rai/qt/qt.cpp:1415:6: note: candidates are:
In file included from /usr/include/qt5/QtCore/QtCore:77:0,
                 from /usr/include/qt5/QtGui/QtGuiDepends:2,
                 from /usr/include/qt5/QtGui/QtGui:3,
                 from ../rai/qt/qt.hpp:9,
                 from ../rai/qt/qt.cpp:1:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   candidate expects 3 arguments, 2 provided
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 2 provided
ninja: build stopped: subcommand failed.
```

**Comment by CathalT** [comment]
@androm3da I'll take a look when I get home from work this evening. (I'm on GMT).

How many versions of Qt do you intend on supporting?
Looks like lambdas were added to the singleShot timer API in Qt 5.4. that's pretty old...

I see from the build instructions its 5.x , any thoughts of pinning it to a higher version?

**Comment by CathalT** [comment]
Yeah just going over it now, implementing timers that are compatible with every version of Qt 5 will require a few changes.

Two options:
1.) Pin the Qt version to something >= Qt 5.4. (obviously the easy way out, but worth it for the newer features and APIs)

2.) I'll fix up the QTimer code to support all versions of Qt5, but will take me a bit longer.

My only question is Raiblocks trying to be backwards compatible with Qt versions?

I'll make sure to fix the issues I introduced ASAP.
After that will try contribute when I get a chance, noticed a few other issues with the Qt code.

**Comment by kvrban** [comment]
my vote: options 1

**Comment by CathalT** [comment]
Ok I see now:

https://launchpad.net/ubuntu/trusty/+package/qt5-default

Trusty only has Qt 5.2.1 by default, my bad that went over my head.
Still, is there some way we could manually update to a newer Qt?

Anyway here are some solutions to the timer issue if we are to support older versions:

Solution 1: Old school QTimer, which calls back on a member function of the QObject.
(Few changes needed for this, the current code isn't really following Qt best practices.)

qt.hpp
```c++
...
class self_pane : public QObject
{
public:
	...
	void onTimer();
...
```
qt.cpp
```c++
rai_qt::self_pane::self_pane (rai_qt::wallet & wallet_a, rai::account const & account_a) :
...
{
...
	QObject::connect (copy_button, &QPushButton::clicked, [this]() {
		this->wallet.application.clipboard ()->setText (QString (this->wallet.account.to_account ().c_str ()));
		copy_button->setText ("Copied!");
        QTimer::singleShot(std::chrono::milliseconds(2000).count(), this, &rai_qt::self_pane::onTimer);
	});
}

void rai_qt::self_pane::onTimer()
{
    copy_button->setText("Copy");
}
```

Or implement a wrapper which emulates the current lamda versions:
(Less work than the oldschool way, but not battle hardened.)
```c++
class QTimerWrapper : public QObject
{

public:
    static void singleShotTimer(std::chrono::milliseconds ms, std::function<void()> _lambda)
    {
        new QTimerWrapper(ms, _lambda);
    }

private:
    QTimerWrapper(std::chrono::milliseconds ms, std::function<void()> _lambda) : lambda(_lambda)
    {
        QTimer::singleShot(ms.count(), this, &QTimerWrapper::onTimer);
    }
    void onTimer()
    {
        lambda();
        deleteLater(); //Qt will put a message on the event queue to destroy self later.
    }
    std::function<void()> lambda;
};
```
Usage:
```c++
QTimerWrapper::singleShotTimer(std::chrono::seconds(2), [this]()
{
    copy_button->setText("Copy");
});
```

Again if I had the time I'd love to help reworking the UI and remove most of those timers.
At the moment I'm just trying to get us into a stable state without compilation errors.

**Comment by androm3da** [comment]
I'd like to keep working with the existing Trusty builds, it seems a shame to lose compatibility with this distro over such a small change.

Can we add a feature test that looks for the lambda and reverts to something simpler if it's not there?

**Comment by CathalT** [comment]
Is there no way to update the distro with a newer version Qt?

I think getting something that compiles across the board is a cleaner and easier solution, I can re-work it if we're stuck with Qt 5.2.1. (Which is looking like where we are headed.)

Seems really messy changing implementations based on qt versions and also I wouldn't know where to start with writing a CMake feature test...

**Comment by androm3da** [comment]
We're stuck with whatever Canonical decided to ship.  They likely only take bugfixes to the Qt release that comes with Trusty.  Binding ourselves to a newer Qt would mean that we can no longer ship on Trusty.  But your commit is the only feature we're leveraging that would prevent us from building on Trusty.

Maybe for the release after this one it would make sense to not support Trusty but as it exists today we have folks who are using the raiblocks wallet on Trusty.

**Comment by cryptocode** [comment]
Seems like changing the code is the easiest way to resolve this.

FWIW, I believe there's both Qt 5.8 and 5.9 PPA's for Trusty. One way to support it would be a build script that ships a RaiBlocks PPA to launchpad, and that one can include external PPA dependencies IIUC. Trusty users would then install the RaiBlocks PPA. Probably a ton of work getting this right, though.

**Comment by CathalT** [comment]
Yeah no problem, I'll make the code change, but as the UI is developed you may see more issues like this. Qt 5.2.1 is pretty old.

Also how are you shipping to Windows and Mac? Qt isn't pre-installed on most machines right?
I'm assuming you have to bundle it?

**Comment by cryptocode** [comment]
@CathalT @androm3da if going back to alarm timers, it would be nice to coordinate this with the steady_clock timers PR, otherwise things won't compile. 

Maybe merge the steady_clock PR first, then make a Qt solution based on that. Or I can rebase and do another system_clock replacement.

**Comment by CathalT** [comment]
Think I'll just go with the standard Qt timers its the safest and cleanest solution. No messing about, just a bit more effort than the fire and forget ones with the lamdas.

**Comment by rainbyte** [comment]
As I understand (and after talking about Qt version with @lukealonso ), CI build is **not** using Ubuntu Trusty. The correct Ubuntu version which is being used now for RaiBlocks is 16.04 Xenial (look Dockerfile [here](https://github.com/clemahieu/raiblocks/blob/master/docker/ci/Dockerfile)), which I think it has Qt 5.5 in the repo.

There is a PPA for new Qt versions [here](https://launchpad.net/~beineri) (even Qt 5.10), and I have updated Dockerfile [here](https://pastebin.ca/3958333) (but I didn't test it yet).

I think it would be better for RaiBlocks to define minimal Qt version being used and stick to it until there is a reason to change. Maybe Qt 5.9 could be a good choice, because it is LTS and will be supported lot of time.

**Comment by cryptocode** [comment]
@rainbyte Do you recommend putting a RaiBlocks ppa on launchpad with a ppa-dependency on Qt? That way the user wouldn't have to install the Qt ppa manually, but simply install the RaiBlocks ppa.

**Comment by rainbyte** [comment]
I'm not sure if RaiBlocks PPA is best choice for Ubuntu users, maybe it would be good idea to ask them, but also to take into account current supported Ubuntu versions:

trusty (14.04 LTS) -> Qt 5.2.1
**xenial (16.04 LTS) -> Qt 5.5.1** (this one is being used in RaiBlocks Travis CI image)
zesty (17.04) -> Qt 5.7.1
artful (17.10) -> Qt 5.9.1
bionic (18.04 LTS) -> Qt 5.9.3

If Qt 5.9 LTS could be used as RaiBlocks minimum Qt version, then custom PPA would be needed just for old Ubuntu versions, and versions >= 2017 could be supported by default package without any PPA

**Comment by cryptocode** [comment]
@rainbyte yes, I'm specifically thinking about Trusty users.

**Comment by rainbyte** [comment]
Today Trusty users need a PPA, because RaiBlocks is based on Xenial, which has Qt 5.5.1.

**Comment by cryptocode** [comment]
OK, I somehow thought I they currently got binaries assuming Qt 5.2.

**Comment by rainbyte** [comment]
I thought that too, but you can look Dockerfile [here](https://github.com/clemahieu/raiblocks/blob/master/docker/ci/Dockerfile), which uses Ubuntu 16.04 Xenial... If RaiBlocks is compatible with Trusty Qt 5.2 is just by luck (it is not being tested).

**Comment by androm3da** [comment]
"Raiblocks is based on ..." should be instead described as "Raiblocks' docker CI image is based on..."

But we can create binaries for more platforms than the CI is configured to support.  Indeed Trusty builds worked until right before PR #508 

It would be ideal if our CI supported as many different distros as we intended to support, but it's not the case just yet.

**Comment by rainbyte** [comment]
@androm3da , you are right, my bad... already fixed it to avoid confusion.

Maybe it would be a good idea to think about some kind of flatpak, snap or appimage package. That way distro would be irrelevant if correct lib is included in the package.

**Comment by CathalT** [comment]
Is it worth fixing this? Considering:
https://www.reddit.com/r/RaiBlocks/comments/7sp82m/developer_update_7_24118_desktop_wallet_update/
