### ISSUE TITLE
Using rai_node and rai_wallet messes up 

### ISSUE THREAD

**Issue by stefonarch** [clemahieu/raiblocks#528]
**Description of bug:**
Already having used the rai_wallet (latest git checkout) and     then setting up (with a different config.json) the rai_node as described here: https://github.com/clemahieu/raiblocks/wiki/Running-rai_node-as-a-service rovines data.ldb

When   switching back  to rai_wallet (exchanging again the config.json) rai_wallet  was working but showed   always and forever 215 blocks not computed.

**Steps to reproduce the issue:**
1. use rai_wallet, sync, close
2. Rename config.json and follow https://github.com/clemahieu/raiblocks/wiki/Running-rai_node-as-a-service , run it a while, stop it.
3. Switch back to the old config.json and open rai_wallet

**Describe the results you received:**

There will be always hundreds of unprocessed blocks and a more-than-normal upload traffic

**Describe the results you expected:**

It would be fine to be able using both.

**Additional information you deem important (e.g. issue happens only occasionally):**

I think this is normal behaviour but can  give bad experience. 
Possible solutions:
a) a warning here: https://github.com/clemahieu/raiblocks/wiki/Running-rai_node-as-a-service
b) custom configuration path instead of fixed  ~/Raiblocks

**Environment**:

**logs**

**Comment by chpio** [comment]
> forever 215 blocks not computed

Dupe of #505?

> b) custom configuration path instead of fixed ~/Raiblocks

Isn't the `--data_path` argument covering this?

**Comment by stefonarch** [comment]
a) not sure, what I see that with a fresh downloaded data-ldb (from https://yadi.sk/d/fcZgyES73Jzj5T) I have no numbers in brackets for some hours, after half a day they are at (15) and hardly disappear.

b) If I had seen this option before... but I think it's still good a warning/hint on the guide mentioned above.

In future a custom path option at first launch could be implemented IMHO.

**Comment by stefonarch** [comment]
In the end I'm not sure if the sticked numbers of blocks left  to process are related to using _wallet and _node with the same data-ldb.
