### ISSUE TITLE
[Feature] To add a --version flag to rai_node CLI to help figure out the current version

### ISSUE THREAD

**Issue by pramttl** [clemahieu/raiblocks#548]
## Current behavior

There is no easy way to determine the version from the CLI

## Expected behaviour
```
rai_node --version
$ 9.0
```

**Comment by argakiig** [comment]
Resolved with
https://github.com/clemahieu/raiblocks/commit/88dd3c428ffb46d7864e25f5eb31266db628c2b1

**Comment by cryptocode** [comment]
@argakiig maybe a newline after the version number? std::endl is missing

**Comment by argakiig** [comment]
Your right, Thank you for point it out, has been updated https://github.com/clemahieu/raiblocks/commit/76de50c71c9d017c51330c8ec1dfcdf7d19b740c
