### ISSUE TITLE
work.cpp "work_validate" inverse success return value (updated)

### ISSUE THREAD

**Issue by CathalT** [clemahieu/raiblocks#549]
https://github.com/clemahieu/raiblocks/blob/master/rai/lib/work.cpp#L8 
~~Should return true if the work provided is valid right?~~

Returns false if work is valid...

~~RPC "work_validate" returns 0 instead of 1 , https://github.com/clemahieu/raiblocks/blob/master/rai/node/rpc.cpp#L4022~~

~~Docs specify "1" but don't elaborate:
https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#work-validate~~

Edit: Ok so the confusion lies with the work_validate function returning "true" for failure and "false" for success.

**Comment by SergiySW** [comment]
RPC "work_validate" returns "1" if work is valid. You can change it to "true" if required
https://github.com/clemahieu/raiblocks/blob/master/rai/node/rpc.cpp#L4022   

> https://github.com/clemahieu/raiblocks/blob/master/rai/lib/work.cpp#L8
> Should return true if the work provided is valid right?

Nope, if work is invalid, result of that function is true. Work value should be >= publish_threshold

**Comment by CathalT** [comment]
Yeah I was thinking, but the name of the function and the return type threw me off...

```c++
bool work_validate()
{
    if (invalid)
    {
        return true;
    }
    else
    {
        return false;
    }
}
```

Doesn't make much sense does it?
