### ISSUE TITLE
Watch-only mode

### ISSUE THREAD

**Issue by HostFat** [clemahieu/raiblocks#56]
Related with #55 

The node should be able to see incoming translations without having the private keys (or any private keys) of the watched addresses.

**Comment by clemahieu** [comment]
The pending RPC lists the hash of all blocks the given account has not yet received.  https://github.com/clemahieu/raiblocks/commit/7cde941f2ec61b05d9711fe65dc6205e76330b05  

The account_balance RPC also will sum up the total pending.  https://github.com/clemahieu/raiblocks/commit/1b308d82343ac65ccc315be26c1da8876e660faf

Let me know if you think this will be good.

**Comment by HostFat** [comment]
Yes, it seems good :)
