### ISSUE TITLE
Remove Bitgrail from accredited exchanges

### ISSUE THREAD

**Issue by embatbr** [clemahieu/raiblocks#568]
It is clear now that Bitgrail is manipulating the market to buy XRB at a low price and sell it when Binance happens. You should distance yourselves from this, and remove any mention of Bitgrail being a trusted partner.

**Comment by polyzen** [comment]
Seems plausible, but could you include some sort of proof?

**Comment by embatbr** [comment]
Bomber's twitter, RaiBlocks reddit...

I'll get some to paste here soon.

**Comment by brightmonkey** [comment]
This is not a bug report, please close the issue.

**Comment by embatbr** [comment]
How to suggest these things then?
