### ISSUE TITLE
Latest commit of rai_node seg faults in osx

### ISSUE THREAD

**Issue by vano21** [clemahieu/raiblocks#598]
**Bug**

- The latest commit 257af11d under OSX segfaults. 

**Steps**

 1. Compile the latest commit 257af11d under OSX.

 2.  Run rai_node as a daemon.

**Issue**

- Segfaults after a short time. 

**Logs**

- [log_2018-02-08_13-46-12.39.log](https://github.com/clemahieu/raiblocks/files/1707181/log_2018-02-08_13-46-12.39.log)

- [rai_node_2018-02-08-134654_MacPro.crash.txt](https://github.com/clemahieu/raiblocks/files/1707191/rai_node_2018-02-08-134654_MacPro.crash.txt)

**Comment by cryptocode** [comment]
@vano21 log-file output?

**Comment by vano21** [comment]
https://github.com/clemahieu/raiblocks/files/1707113/rai_node_2018-02-08-134654_MacPro.crash.txt

**Comment by cryptocode** [comment]
@vano21 i meant the log-file produced by rai_node

**Comment by vano21** [comment]
[log_2018-02-08_13-46-12.39.log](https://github.com/clemahieu/raiblocks/files/1707182/log_2018-02-08_13-46-12.39.log)

**Comment by cryptocode** [comment]
Thanks

**Comment by stefonarch** [comment]
Similar here with Linux, nano_wallet segfaults after some minutes with no useful messages using old settings and ledger (diff of settings is not relevantIMHO)
Rename ~/RaiBlocks solves the segfault, for the moment it's at 1 (490'000)

**Comment by lukealonso** [comment]
We should try to isolate if this is the hash2 changes, or my bootstrap improvements.

**Comment by PlasmaPower** [comment]
It's definitely the hash2 changes. Segfault with `RELWITHDBGINFO` build:

```
0x00005555558886d3 in rai::block_store::representation_add (this=0x5555561aa4a8, transaction_a=0x5555562b1960, source_a=..., amount_a=...) at /home/lee/programming/cpp/raiblocks/rai/secure.cpp:2503
2503            auto source_rep (source_block->representative ());
```

Assert fails with `DEBUG` build:

```
nano_wallet: /home/lee/programming/cpp/raiblocks/rai/secure.cpp:2706: virtual void {anonymous}::ledger_processor::send_block(const rai::send_block&): Assertion `!hash2.is_zero ()' failed.
```

I've tried manually rerunning the DB migration, but it didn't help.

**Comment by cryptocode** [comment]
@PlasmaPower it also happens when starting from scratch
