### ISSUE TITLE
Data never seems to flush to disk

### ISSUE THREAD

**Issue by eirikrye** [clemahieu/raiblocks#599]
rai_node compiled from the `master` branch on February 3rd.

I am collecting some metrics for my node on this page:

https://nanowat.ch/stats/node

For some reason, for the past five days, the file size of my ledger database has literally been unchanged at 2541572096 bytes. This happened before I recompiled from source.

I have made sure the data path has not accidentally changed, somehow:

```
# find / -name "data.ldb"
/var/data/raiblocks/data.ldb

# lsof -p 24400 | grep .ldb
rai_node 24400 raiblocks  mem       REG                8,1 2541572096  3670030 /var/data/raiblocks/data.ldb
rai_node 24400 raiblocks  mem-r     REG                8,1       8192  3670020 /var/data/raiblocks/data.ldb-lock
rai_node 24400 raiblocks    3ur     REG                8,1       8192  3670020 /var/data/raiblocks/data.ldb-lock
rai_node 24400 raiblocks    4u      REG                8,1 2541572096  3670030 /var/data/raiblocks/data.ldb
rai_node 24400 raiblocks    5w      REG                8,1 2541572096  3670030 /var/data/raiblocks/data.ldb
```

I restarted the node yesterday, on February 7, but this has had no effect on the ledger size at all.

My initial thought is that it is using reclaimed space after I ran the `--vacuum` command to clean up the database, however that was done almost a week prior on January 26.

**Comment by cryptocode** [comment]
@eirikrye maybe there's enough free pages in lmdb. Can you do a ldb copy, run it for a while, see if the binary diff has changes / timestamp changes / etc.

**Comment by eirikrye** [comment]
You seem to be correct.
