### ISSUE TITLE
Try to updaate but not loading now 

### ISSUE THREAD

**Issue by bapparabi** [clemahieu/raiblocks#6]
Hi 
I try to update to latest version of wallet ..everything done successful ..but now the wallet is not opening ..
When i click the wallet icon it blink for 2-3 second then nothing is happening  ..

i try to uninstall it and reinstall but same problem persist ..Now old version is also not working also .. do you know what is the problem .. 
also i am not getting error  also solve it can you tell any solution

**Comment by HostFat** [comment]
Does it crash with the last version? 7.4.9

**Comment by clemahieu** [comment]
Loading problems should be fixed in 7.5.0

https://github.com/clemahieu/raiblocks/releases/tag/V7.5.0

**Comment by bapparabi** [comment]
now wallet is not unlocking ..its say lock ..i tyr to unlock it but its not working
