### ISSUE TITLE
"clear keys" blinking,  in import seed

### ISSUE THREAD

**Issue by HostFat** [clemahieu/raiblocks#68]
If the user leave the space empty, where he needs to enter "clear keys", then the text with "Type 'clear keys'  below to confirm:" should blink, or change color, or whatever to get the attention of the user.

**Comment by SergiySW** [comment]
Becoming red now
https://github.com/clemahieu/raiblocks/commit/5072a14dd6ad982bdb77c6a7ce4b911de04c438b
