### ISSUE TITLE
Always Synchronizing

### ISSUE THREAD

**Issue by zheidouz** [clemahieu/raiblocks#7]
My wallet is always synchronizing. my mrai count dont save.
![sdas](https://cloud.githubusercontent.com/assets/9839525/14883062/a5e400c6-0d6e-11e6-8523-aa47a817c7d9.png)

**Comment by HostFat** [comment]
Can you try with the new version?
https://github.com/clemahieu/raiblocks/releases/tag/V7.4.9

**Comment by zheidouz** [comment]
still it synchronizing like forever.

**Comment by zheidouz** [comment]
and now i cant import my wallet seed in the newer version

**Comment by HostFat** [comment]
What do you mean?

Can you try to backup everything, and then uninstall and install it again?

You have to backup this, and delete it after you have uninstalled Raiblock.
C:\Users\[YOURNICKNAME]\AppData\Local\RaiBlocks

**Comment by zheidouz** [comment]
now its disconnected and dont synchronize at all.

**Comment by HostFat** [comment]
Send your logs to the dev:
clemahieu@raiblocks.net

You can find them here:
https://github.com/clemahieu/raiblocks/wiki/Log-files

**Comment by zheidouz** [comment]
here.

**Comment by zheidouz** [comment]
![screenshot 174](https://cloud.githubusercontent.com/assets/9839525/14903497/11f7e150-0dd4-11e6-93c7-7034ffbb7756.png)

**Comment by HostFat** [comment]
Try with the last version
https://github.com/clemahieu/raiblocks/releases/tag/V7.5.0

**Comment by clemahieu** [comment]
Crashes should have been fixed in 7.5.0, if there are synchronization problems, check your firewall and logs to make sure it can connect to other nodes.

**Comment by otantizma** [comment]
I have the same problem now. I tried to mail you my log files, but

> Your message wasn't delivered to clemahieu@raiblocks.net because the address couldn't be found. Check for typos or unnecessary spaces and try again.

I am using version 7.6.1
