### ISSUE TITLE
After clicking backup seed (with/without locked wallet)

### ISSUE THREAD

**Issue by HostFat** [clemahieu/raiblocks#71]
If the wallet is locked, change the text for 5 seconds to something like this:
"Wallet is locked, unlock it to enable the backup"
Then, after the 5 seconds, change the text back to "Backup/Clicboard wallet seed"

Instead, if the wallet is already unlocked, change the text for 5 seconds to something like this:
"Now paste it in a safe place"
Then, after the 5 seconds, change the text back to "Backup/Clicboard wallet seed"

**Comment by SergiySW** [comment]
https://github.com/clemahieu/raiblocks/commit/5072a14dd6ad982bdb77c6a7ce4b911de04c438b
