### ISSUE TITLE
Replace "Mrai from raw" and "Mrai to raw"

### ISSUE THREAD

**Issue by ghost** [clemahieu/raiblocks#8]
For conversion of units, you could do something like:

To Raw
{ "action": "to_raw", "unit": "Grai/Mrai/Krai/Rai/mrai/urai","amount": "1" }

From Raw
{ "action": "from_raw", "unit": "Grai/Mrai/Krai/Rai/mrai/urai","amount": "100000000000000000" }

**Comment by mikerow** [comment]
There are already dedicated rpc for rai,Krai,Mrai conversion. This issue can be closed.
