### ISSUE TITLE
RCP command to force bootstrap to specific peer

### ISSUE THREAD

**Issue by SergiySW** [clemahieu/raiblocks#81]
like
`{ "action": "bootstrap", "peer": "::ffff:128.199.199.97:7075" }`

**Comment by thinhdxbp** [comment]
như
{ "action": "bootstrap", "peer": "::ffff:128.199.199.97:7075" }

**Comment by SergiySW** [comment]
Done
https://github.com/clemahieu/raiblocks/commit/34e9a9c943cf74d669100ac9fa89939af193a5d0
