### ISSUE TITLE
"This account doesn't exist on the blockchain yet." on raiblock's site

### ISSUE THREAD

**Issue by milen16** [clemahieu/raiblocks#82]
solution ?

**Comment by SergiySW** [comment]
It means you didn't receive ant Mrai yet. Send some Mrai to it

**Comment by milen16** [comment]
http://prntscr.com/eao5eo
how about this?

**Comment by SergiySW** [comment]
https://github.com/clemahieu/raiblocks/wiki/Troubleshooting-and-Missing-transactions
