### ISSUE TITLE
Sending no rai?

### ISSUE THREAD

**Issue by nkarm1** [clemahieu/raiblocks#94]
please help me with this. 
is this with the wallet? i lost my rai. didn't reflect transactions in the network.

my wallet created transactions that didnt reflect in the network :((( now the Mrais are gone. 
please help me. 
![photo6165987412895967145](https://cloud.githubusercontent.com/assets/25716197/23331251/19ce1c16-fb9d-11e6-833e-5f1188b23057.jpg)

**Comment by nkarm1** [comment]
look at this hash, E21A732007A8164FF14B6FA47A3CB06BDC7132F2B32A2487359CC88C48642FC0
it says that the rai are sent. but looking at this (the receiving wallet) it didnt reflect.

https://raiblockscommunity.net/account/index.php?acc=xrb_153ptn7jdero1fu18q3azo3tc4ciiihc7fk5gbyjnrsok3zah9ez1f567tps

**Comment by HostFat** [comment]
Is you wallet synchronized?
Is you wallet unlocked?

**Comment by nkarm1** [comment]
Its not synchized. But the rais are gone. I checked the website.

**Comment by HostFat** [comment]
You have to be sure that it is unlocked, and that it is synchronized.

**Comment by nkarm1** [comment]
So my rais are gone? For life?

**Comment by mikerow** [comment]
Check it's unlocked and sync.

2017-02-25 15:28 GMT+01:00 nkarm1 <notifications@github.com>:

**Comment by nkarm1** [comment]
Yeah i know my mistake. All i want to know is that are my rais gone? Because by checking at the hash and the recipient address. It did not matched. At the recipient it wasn't there

**Comment by HostFat** [comment]
Is your wallet locked? YES/NO
If YES, then unlock it.

Is you wallet synchronized? YES/NO
If NO, wait for its synchronization.

**Comment by nkarm1** [comment]
It unlocked. Before v. 8.1, it's synced. After update never gone insync. So i moved my funds. On the sender it reflects in the network, but not on the recipient. 
 And it is possible to have an infinite creation of account in your wallet? Cause i can create account more than 200 when i tried.

**Comment by mikerow** [comment]
Post here:
Account sender
Tx hash
Account receiver

2017-02-25 15:56 GMT+01:00 nkarm1 <notifications@github.com>:

**Comment by nkarm1** [comment]
Post here:
Account sender
Tx hash
Account receiver

sender : xrb_1cay8h9kywj86udafgpwys7ueh8rsngxhr5zugpifzbmaba67st13dook396

tx: EB7C5131D2C73DFC1EFD8B233B263FC47D0324076B1F259168C290D22AE4E905,
C5F52029518E20F4E4AED3985777BD4447DA03865CC2212A3E6A9ABC54546C3D,
E21A732007A8164FF14B6FA47A3CB06BDC7132F2B32A2487359CC88C48642FC0,
etc.

recipient: 	xrb_153ptn7jdero1fu18q3azo3tc4ciiihc7fk5gbyjnrsok3zah9ez1f567tps


check it. everything there was my last tx. no reflections to each other.

**Comment by mikerow** [comment]
The tx you posted are in the blockchain, I don't understand your problem.

2017-02-25 16:10 GMT+01:00 nkarm1 <notifications@github.com>:

**Comment by nkarm1** [comment]
yes they are. but they should be recorded also in the recipient right?
