### ISSUE TITLE
[Wallet] Synchronizing

### ISSUE THREAD

**Issue by betaa1337** [clemahieu/raiblocks#97]
Hey everyone,

I

have a problem. my wallet is on status "Synchronizing" forever. I really need your help.

Logs:
http://www.mediafire.com/file/fmezr6bpdv1xiey/log_2017-03-05_13-12-55.0.log

**Comment by SergiySW** [comment]
Why do you shut down wallet after 1 minute of sinchronizing? Wait

**Comment by betaa1337** [comment]
i closed the programm cuz it only sync

**Comment by clemahieu** [comment]
Please use version 7.8.3 https://github.com/clemahieu/raiblocks/releases/tag/V7.8.3

**Comment by chelly13** [comment]
How to create raiblock account
